; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Sat Mar 13 2021 00:59:11 GMT+0800 (中国标准时间)

M118 P2 S"//action:cancel"
