; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Sat Mar 13 2021 00:59:11 GMT+0800 (中国标准时间)

M83 ; relative extruder movement
G1 E-2 F3600 ; retract 2mm
M106 S0           ; turn off our print cooling fan
G91 ; relative axis movement
G1 Z3 F500 ; up 3mm
G90 ; absolute axis movement
G1 H1 X180 F6000 ; park the X carriage at -48mm